# GoReleaser configuration for ruslan-cli
# https://goreleaser.com

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: ruslan-cli
    binary: ruslan-cli
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: ruslan-cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

# Homebrew tap configuration
brews:
  - name: ruslan-cli
    repository:
      owner: dautovri
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/dautovri/ruslan-cli
    description: "CLI tool for managing HashiCorp Vault across multiple GCP/GKE environments"
    license: MIT
    install: |
      bin.install "ruslan-cli"
      
      # Install shell completions
      bash_completion.install "completions/ruslan-cli.bash" => "ruslan-cli"
      zsh_completion.install "completions/ruslan-cli.zsh" => "_ruslan-cli"
      fish_completion.install "completions/ruslan-cli.fish"
    test: |
      system "#{bin}/ruslan-cli", "--help"

# Docker images (optional)
dockers:
  - image_templates:
      - "ghcr.io/dautovri/ruslan-cli:{{ .Version }}"
      - "ghcr.io/dautovri/ruslan-cli:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
